scripts/common/cb_create_gmond_config_file.sh
Address issue 57 from ibmcb/cbtool.  Additional explanation available in issue 57 text.
=> issue 57 changes - fix gmond configuration file generation

lib/clouds/osk_cloud_ops.py, scripts/cassandra_ycsb/cb_ycsb.sh, scripts/common/cb_common.sh
Allow hostnames in ACCESS URL to contain '-'.  ( A valid character in hostnames.)
=> Translate _dash_ to '-' in OSK access URL value.

lib/remote/network_functions.py
this is centos specific modification
=> minor modification to accomodate centos specfic parsing

README.md
=> change email

README.md
List recent SPEC release in README
=> List recent SPEC release in README

lib/operations/active_operations.py
Fix to unbreak non-VPN clouds. Sorry about that guys.
Stupid mistake.
=> Fix to unbreak non-VPN clouds. Sorry about that guys.

lib/api/api_service_client.py
A missing keyword argument broke many of the functions in the api_service_client helpers
1. The 'samples' parameter is missing. Let's fix that.
2. Also fix some whitespaces that don't need to be there.
=> POST-FREEZE: lib/api/api_service_client.py: Missing keyword argument 

configs/templates/internal_options.txt, lib/operations/passive_operations.py
trac ticket URL: https://pro.spec.org/private/trac/osg/cloud/iaas/ticket/115
=> Fixes for SPECCloud "trac ticket" #115

lib/api/api_service_client.go, lib/clouds/ec2_cloud_ops.py, lib/clouds/libcloud_common.py
libcloud volume support and multi-cloud cleanup operations were broken.
=> libcloud bugfixes

lib/clouds/slr_cloud_ops.py
Fixed the is_vm_running() and get_instances() to check the provisionDate to properly determine when the provisioned VM is actually ssh-able.
=> Fix provision error for when VM is ssh-able

cbact, configure
Fix the lack of log messages for actuators (async operations/API)
This commit fixes a bug that prevented actuators from directing logs
to the appropriate files.
It also fixes the very same bug with the automated installer/configure
utility.
=> Fix the lack of log messages for actuators (async operations/API)

regression/real_application_regression_test.py, regression/real_multicloud_regression.py, regression/real_multicloud_regression_parallel.sh
Improvements and optimizations for the regression tests on Real Clouds
This commit introduces a crude but yet effective mechanism to allow the
running of regression tests in ALL clouds in parallel. It will be of
great importance to properly test future code changes, improving the
tool's stability.
=> Improvements and optimizations for the regression tests on Real Clouds

configs/cloud_definitions.txt, configs/templates/_as.txt, lib/clouds/as_cloud_ops.py
Initially, no support for volume attachments (the libcloud backend does not allow it) or for
vmcapture (ditto).
=> Libcloud-based Azure Adapter.

lib/clouds/osk_cloud_ops.py
When creating VMs in parallel, cbtool creates novaclient client object
in main thread and invokes methods on that object in multiple worker
threads. This approach could cause random failures because novaclient
is not thread-safe. A main issue is that novaclient provides methods
to access image and network APIs and those methods change client
object's service_type attribute, which is one of the components used
to generate request URL. So for example, if a worker thread calls
image API when there are other threads calling compute APIs, the latter
would fail. I observed the issue consistently when I ran SPECcloud's
yscb baseline script (I replaced its cbtool with the latest vesion)
on systems which had latest version of novaclient installed.
The change works around the issue by using …
=> Use glanceclient to access OpenStack image API

scripts/common/cb_common.sh
1. I previously made an attempt to detect Amazon NVMe devices on Compute-based instances.
The patch didn't work. =) This makes it work.
2. Another PR also has a patch to fix the way "run_limit" works inside of cb_common.sh
I missed a part of that patch, so this includes it. Having it here won't break anything
unless you're actually using it (Which only we are)
=> Amazon NVMe block device detection

configs/templates/PUBLIC_dependencies.txt
The JSON-parsing command 'jq' is now a dependency.
=> Add the 'jq' to dependencies.

lib/clouds/shared_functions.py
I'm not sure why this was never merged, but a long time ago, I found
a few race conditions in the simcloud path of the regression tests
that prevented the tests from passing.
This fixes those race conditions.
=> Simcloud race conditions

lib/operations/passive_operations.py, lib/stores/redis_datastore_adapter.py
This is another regression: I previously committed support to allow
reset counters to work properly, but this particular part of the
change was lost.
=> Reset counters regression

lib/clouds/gce_cloud_ops.py
Whoops! I put in one too many httplib2shim calls.
=> Unbreak GCE. =)

configs/templates/PUBLIC_dependencies.txt, docker/build_common.sh, docker/build_orchestrator.sh, docker/orchprereqs/Dockerfile-centos_cb_orchprereqs, docker/orchprereqs/Dockerfile-ubuntu_cb_orchprereqs, docker/workload/Dockerfile-centos_cb_netperf, scripts/giraph/dependencies.txt, scripts/hadoop/dependencies.txt, scripts/mongo_ycsb/dependencies.txt, scripts/oldisim/dependencies.txt, scripts/oldisim/virtual_application.txt, scripts/open_daytrader/virtual_application.txt, scripts/scimark/dependencies.txt, scripts/specjbb/dependencies.txt, scripts/sysbench/dependencies.txt
Fixes for the automated installer dependencies, including the automated creation of Docker images (both Orchestrator and Workloads)
Additional fixes for dependencies for specific workloads (e.g. scimark)
Additional fixes for definition of specific workloads (e.g., oldisim)
=> Fixes for Docker images and dependencies

docker/workload/Dockerfile-centos_cb_nullworkload, docker/workload/Dockerfile-ubuntu_cb_nullworkload, kvm-qemu/base/ubuntu_commands, kvm-qemu/build_common.sh
While testing the automatic building of both Docker and KVM/QEMU images a couple of additional bugs were uncovered. This PR fixes those.
=> Bugfix for the automated building of images

scripts/common/cb_common.py, scripts/common/cb_common.sh, scripts/common/cb_hadoop_common.sh
Small bugfixes for problems uncovered while test Hadoop/KMeans on "Pure Docker" with SPEC Cloud Parameters.
=> Hadoop/KMeans bugfixes on PDM (SPEC Cloud)

docker/build_common.sh, docker/build_workloads.sh, docker/installtest/Dockerfile-ubuntu_cb_installtest, docker/orchprereqs/Dockerfile-centos_cb_orchprereqs, docker/orchprereqs/Dockerfile-ubuntu_cb_orchprereqs, docker/workload/Dockerfile-centos_cb_nullworkload, docker/workload/Dockerfile-ubuntu_cb_nullworkload, kvm-qemu/base/getmyips.sh, kvm-qemu/base/ubuntu_commands
Just making sure that Docker and KVM-QEMU images can be built by anyone, outside my particular private environment.
=> Bugfixes for Docker and KVM-QEMU image building.

scripts/common/cb_acmeair_common.sh, scripts/memtier/dependencies.txt, scripts/mongo_acmeair/cb_modify_hosts.sh, scripts/mongo_acmeair/cb_modify_shard.sh, scripts/mongo_acmeair/cb_restart_liberty.sh, scripts/mongo_acmeair/cb_restart_mongo.sh, scripts/mongo_acmeair/cb_restart_mongo_cfg.sh, scripts/mongo_acmeair/cb_restart_mongos.sh, scripts/mongo_acmeair/cb_run_acme.sh, scripts/mongo_acmeair/dependencies.txt, scripts/mongo_acmeair/template_server.xml, scripts/mongo_acmeair/virtual_application.txt
Fixes for the (significant) changes on the workload "mongo_acmeair" application (AirLine travel reservation).
=> Fixes for workload "mongo_acmeair"

scripts/common/cb_common.sh
This commit fixes several small but significant bugs on the
"automount_data_dirs" function (and associated functions).
In addition to bugfixes, this function now fully and properly supports
docker volumes (which are in fact, host directories mapped).
=> Data volume mount bugfixes

lib/auxiliary/config.py
Sometimes, in a CI/CD environment, we have customizations to the templates that don't belong in production or in the repository, so we use symbolic links.
This change simply follows a link to see if the template is a broken link. If it's broken, we just skip that link and move on without bailing out.
=> Skip broken symlink templates

lib/clouds/kub_cloud_ops.py
A simple bugfix to ensure this adapter is compatible with K8s
=> Kubernetes adapter bugfix

util/setuphelm.sh
1. The registry was crashing due to an obscure bug upstream when running inside the cluster [fixed]
2. We needed to define an additional service for VPN to work properly instead of using the Pod IP address (which can change) [fixed]
=> k8s Fix for private registries and VPN connectivity

lib/auxiliary/gui.py
Upstream introduced a backwards-incompatible change.
=> Fixed broken update to twisted

scripts/common/cb_common.sh
We have to startup the docker container a little differently
with the new cloud-init user changes we had in the last few PRs.
=> nested: permissions issue

lib/clouds/dok8s_cloud_ops.py, lib/clouds/kub_cloud_ops.py, util/setuphelm.sh
1. Sometimes k8s `delete()` operations hang. If we're a cloud-provided k8s, then don't let that stop us.
2. Also: DO-provided k8s has some quirkiness with their API that we have to overcome.
=> k8s bugfixes

scripts/cassandra_ycsb/cb_restart_seed.sh, scripts/cassandra_ycsb/virtual_application.txt
This implements the changes we've discussed for
"AUTO" for the cassandra heap size.
=> cassandra: manage the heap size

util/setuphelm.sh
As a reminder: We use this shell script to "boostrap"
a dynamically provisioned k8s cluster (provided by a service)
into a workable state:
1. We install a docker registry into the cluster
2. We configure the workers to use it
3. We install a VPN service directly into the cluster as well.
This change makes this possible without needing an external load
balancer and it does it without need to login directly to the
workers any longer, nor do we need to setup any additional
firewall rules.
=> k8s: dynamic k8s benchmarking improvements

lib/operations/active_operations.py, lib/operations/base_operations.py
This change modifies the existing round-robin scheduling to make sure
that we keep all VMCs "equally full" and not simply just do round-robin
scheduling.
We do this by adding an additional counter at the VMC level. This is necessary
because access to the counter for scheduling has to be synchronized by
all VM attach operations so that the counter is increased only when a VMC
is actually being selected. This counter works as a 3rd type of admission
control, similar to regular admission control and speculative admission
control, but specifically for the number of VMs per VMC. The other admission
control counters only restrict the total "global" number of VMs or AIs
and so forth, so we add a 3rd one to do per-VMC capacity scheduling.
This change allows us to keep all VMCs full despite the …
=> Incorporate a semi-real scheduler.

configure, lib/auxiliary/dependencies.py
Among these, are better support for multi-architecture, further
assurance that all packages can be installed in non-interactive mode,
and better suppport for debugging.
=> Improvements for the dependency installer.

lib/remote/process_management.py, lib/remote/ssh_ops.py, util/cbrsync.sh, util/cbssh.sh
1) More details on messages on remote operations
2) Added the ability to properly process SSH in the format required by
IBM cloud. Ideally, these functions should be move into cloud
adapter-specific code.
3) Bugfixes for the utilities `cbssh` and `cbrsync`
=> Improvements and bugfixes for SSH-related issues

scripts/coremark/dependencies.txt, scripts/kernbench/dependencies.txt, scripts/nullworkload/cb_run_nothing.sh, scripts/nullworkload/dependencies.txt, scripts/oldisim/dependencies.txt, scripts/open_daytrader/dependencies.txt, scripts/postmark/dependencies.txt, scripts/redis_ycsb/dependencies.txt, scripts/scimark/dependencies.txt, scripts/scimark/virtual_application.txt, scripts/specjbb/dependencies.txt, scripts/wrk/dependencies.txt
This fix will ensure that images can be automatically configured in any scenario: from the Docker image builder, from the KVM/QEMU image builder or from an already running instance.
=> Fixed dependencies for multiple workloads

regression/real_application_regression_parallel.sh, regression/real_application_regression_test.py, regression/real_multicloud_regression.py, regression/real_multicloud_regression_parallel.sh, regression/regression_test.py, regression/regression_test_experiment_plan.txt
- The Simulated cloud regression test can now be executed against any
already attached cloud (it will printout all the commands required to
reconfigure the cloud to run the regression test successfully)
- The Real Application Regression test has been reworked to be more
flexible.
- The Real Multicloud Regression test has been made more flexible too
=> Improvements and bugfixes for regression testing

lib/operations/passive_operations.py
- It is now possible, simply using CLI/API calls, to create new VM
"roles" on-the-fly. For instance, just by issuing `rolealter mynewrole
size 04-16384`, followed by `rolealter mynewrole imageid1
a573bfb9-4e55-481f-9060-31d757155ded` a new role `mynewrole` is
automatically created
- The CLI/API call "monextract" now includes the creation, within the
experiment data directory, of a small helpe `plot.sh` script, which
allows a user to create/re-create the automatically generated graphs at
any point in time
- Aesthetic improvements on the printing of attributes via `globalshow`
(and associated CLI/API calls, such as `typeshow`)
=> Three relevant improvements for passive operations

docker/orchestrator/Dockerfile-ubuntu_cb_orchestrator, kvm-qemu/base/ubuntu_commands
./install was not working correctly without this change.
=> fix rsyslog dependency

scripts/common/cb_common.sh
In very rare cases, after having stopped SSH in the VM,
it would come back to life right before the container
starts.
This patch catches those cases.
=> nested containers: elusive ssh race condition

LICENSE.txt, __init__.py, setup.cfg, setup.py
We are live! https://pypi.org/project/cbtool/2.0.1/
Upload like this:
$ python setup.py sdist
$ twine upload dist/cbtool-2.0.1.tar.gz --u username -p password
=> Pypi support!

scripts/tpcc/cb_reset_mysql.sh, scripts/tpcc/cb_restart_mysql.sh, scripts/tpcc/cb_run_sysbench.sh, scripts/tpcc/virtual_application.txt
Those fixes were part of the original PR but somehow got overwritten before the merge.
=> Missing fixes for the tpcc workload

scripts/tpcc/virtual_application.txt
=> Fix: wrong load manager start variable

docker/build_base.sh, docker/build_common.sh, docker/build_orchestrator.sh, docker/build_workloads.sh, docker/orchestrator/Dockerfile-centos_cb_orchestrator, docker/orchestrator/Dockerfile-ubuntu_cb_orchestrator, docker/orchestrator/installrlibs.R, docker/push_multi_arch_manifests.sh, docker/workload/Dockerfile-ubuntu_cb_netperf, docker/workload/Dockerfile-ubuntu_cb_parboil, docker/workload/Dockerfile-ubuntu_cb_scimark, docker/workload/Dockerfile-ubuntu_cb_spark, docker/workload/Dockerfile-ubuntu_cb_specjbb, docker/workload/Dockerfile-ubuntu_cb_tpcc, docker/workload/Dockerfile-ubuntu_cb_wrk, docker/workload/Dockerfile-ubuntu_cb_wrk2, kvm-qemu/base/ubuntu_commands, kvm-qemu/build_common.sh, kvm-qemu/build_workloads.sh, lib/auxiliary/dependencies.py
The multi-architecture images will be available on Docker (ibmcb).
Currently, only amd64 and ppc64le are present (I don't have an arm64
machine ready)
Also, additional improvements were made in the KVM-QEMU image building
process.
=> This commits adds support for building multi-architecture Docker images in CB

lib/clouds/libcloud_common.py
Looking up the "status" of a VM is by far the most high-frequency
API call we make to various cloud providers. Because we make it so frequently,
it is prone to failure. If any of these calls fail, it causes the VM creation
to abort prematurely, even in the face of intermittent network activity.
For libcloud-based clouds (at least), let's retry the call, which by default
will re-issue the call every 1-second within a 5-second period until the call
succeeeds.
=> Retry VM lookups

scripts/common/cb_common.py
=> Dangling mysql bug

configs/templates/internal_options.txt, lib/auxiliary/cli.py, lib/operations/active_operations.py, lib/operations/base_operations.py, lib/remote/process_management.py, lib/stores/mongodb_datastore_adapter.py, lib/stores/mysql_datastore_adapter.py, lib/stores/stores_initial_setup.py, scripts/common/cb_create_gmetad_config_file.sh, scripts/common/cb_create_gmond_config_file.sh, util/cbssh.sh
1. So, the whole daemon-forking-daemon thing came back. The typescript 'script' command didn't work. Well, it did, but it doesn't operate correctly when running in parallel. So, I reverted that and added an alternative workaround: Let's make *all* parent daemons (in particular the API and AIDRS daemons) which fork other daemons be in screen sessions, which gives them pseudo-terminals. That seems to do the trick.
Marcio, can I trouble you to run a regression on this?
2. There were additional mysql error handling issues as well that I forgot to fix.
=> super-annoying bugfixes

cb, regression/regression_test.py
Quick fixes to make sure we can run the regression test on simulated
clouds with python3
=> quick fix regression on py3

configs/templates/_do.txt, configs/templates/_gce.txt, docker/base/Dockerfile-cbtoolbt-centos, docker/build_common.sh, docker/orchestrator/Dockerfile-centos_cb_orchestrator, docker/orchestrator/Dockerfile-ubuntu_cb_orchestrator, docker/push_multi_arch_manifests.sh, docker/workload/Dockerfile-ubuntu_cb_nullworkload, lib/clouds/ec2_cloud_ops.py, lib/clouds/gce_cloud_ops.py, lib/clouds/kub_cloud_ops.py, lib/clouds/libcloud_common.py, lib/clouds/pdm_cloud_ops.py, lib/clouds/shared_functions.py, lib/clouds/sim_cloud_ops.py, lib/operations/active_operations.py, lib/operations/base_operations.py, lib/operations/passive_operations.py, lib/stores/mongodb_datastore_adapter.py, regression/regression_test.py
This PR contains all changes required for a successful simulated
regression test, as well as a minimal (basic VM creation) for all
supported clouds.
The problem with daemonization seems to be satisfactorily solved with
python-daemon-3K
=> Set of minimal changes to ensure a complete successful regression test (py3)

configs/templates/_do.txt, configs/templates/_gce.txt, docker/base/Dockerfile-cbtoolbt-centos, docker/build_common.sh, docker/orchestrator/Dockerfile-centos_cb_orchestrator, docker/orchestrator/Dockerfile-ubuntu_cb_orchestrator, docker/push_multi_arch_manifests.sh, docker/workload/Dockerfile-ubuntu_cb_nullworkload, lib/clouds/ec2_cloud_ops.py, lib/clouds/gce_cloud_ops.py, lib/clouds/kub_cloud_ops.py, lib/clouds/libcloud_common.py, lib/clouds/pdm_cloud_ops.py, lib/clouds/shared_functions.py, lib/clouds/sim_cloud_ops.py, lib/operations/active_operations.py, lib/operations/base_operations.py, lib/operations/passive_operations.py, lib/stores/mongodb_datastore_adapter.py, regression/regression_test.py
There was the same issue about the MySQL exception handler that was
fixed in 18d164d685af1a9b5de3e3c100e87b85c6b6359f
Then some typos (obj_attr_list -> _obj_attr_list).
And finally, some files need to be open with buffering.
=> Fix monextract

scripts/iperf/cb_iperf_process.py, scripts/iperf/cb_run_iperf.sh, scripts/iperf/virtual_application.txt
Couple of fixes/changes with iperf workload related to parsing
jitter and loss metrics and also adding an option to view iperf
stats at a regular interval time
=> iperf fixes

configs/cloud_definitions.txt, configs/templates/_zst.txt, lib/clouds/zsk_cloud_ops.py
Signed-off-by: tao.wu <tao.wu@zstack.io>
=> add zstack object operiation library

scripts/common/cb_ycsb_common.sh, scripts/wrk2/virtual_application.txt
1. Make YCSB log on both data generation and as well as the main phase
of each run.
2. Include the 'app_latency' metric (which was missing)
=> YCSB changes

lib/clouds/sim_cloud_ops.py, lib/operations/base_operations.py, lib/operations/passive_operations.py, lib/stores/common_datastore_adapter.py, lib/stores/mongodb_datastore_adapter.py, lib/stores/mysql_datastore_adapter.py
In addition to that, it fixes a problem with newer versions of pymongo.
All these fixes were tested with a complete regression test (using a
simulated cloud).
=> This PR implements a few fixes required for the execution with newer versions of python 3.

lib/clouds/lin_cloud_ops.py
Random password needed strengthening.
=> Linode: API create rules changed for VM passwords
