ibmcb/cbtool

scripts/cassandra_ycsb/cb_ycsb.sh
scripts/cassandra_ycsb/cb_ycsb_common.sh

change cassandra latency units to us from ms. 
add ycsb ouptut support for test-phase similar to load-phase. (dump ycsb output to /tmp/)

ibmcb/cbtool issue 58 changes -

---

lib/auxiliary/value_generation.py

Fix loop condition to only loop until value within range generated.
Generate new random value from distribution within loop. (use eval as recommended by Marcio )
quick test program shows values generated within range and with fewer than _max_retries iterations of loop in rand_dist_gen().
Test program:
```
from sys import path, argv
from time import sleep
import fnmatch
import os
import pwd
home = os.environ["HOME"]
username = pwd.getpwuid(os.getuid())[0]
_path_set = False
for _path, _dirs, _files in os.walk(os.path.abspath(path[0] + "/../")):
for _filename in fnmatch.filter(_files, "code_instrumentation.py") :
if _path.count("/lib/auxiliary") :
path.append(_path.replace("/lib/auxiliary",''))
_path_set = True
break
if _path_set :
break
from lib.api.api_service_client import *
import …
```

Fixes for random number generation.

---

lib/clouds/osk_cloud_ops.py

1) Fix problem with handling of \_dash\_ with OSK parse_authentication_data.  Replacing _dash_ in the CA filename prior to return results in more than 4 items returned. ( and an error from the caller 'too many values to unpack' )
2) Allow for insecure SSL connections with openstack in cases where novaclient insists on using SSLv3.  This in lieu of a real fix to prevent nova client from failing to connect to openstack which does not allow SSLv3.

Fix problem with handling of _dash_ with OSK parse_authentication_data

---

lib/clouds/sim_cloud_ops.py
lib/operations/active_operations.py

SPECCloud uses 'deployment_time' value for sim cloud testing.  With this patch cloudbench honors the user's distribution instead of using default distribution ( uniform|x|x|10|500).

Retrieve user's deploytime distribution for sim clouds if set.

---

scripts/common/cb_hadoop_common.sh

Remove HADOOP_VERSION value generation from common hadoop script because the value is not used.  The hadoop version is obtained correctly in other places correctly by using 'hadoop -v'.   
Also, the regular expression used to find hadoop version was incomplete. To match strings such as '2.x.y' it should also have allowed dots in the pattern. The result of this incorrect regular expression was a misleading message in the log suggesting cbtool could not determine the hadoop version.
Removing this code has not negative behavior and reduces confusion from logs.

Remove unused code used to determine hadoop version.  

---

configs/templates/_digitalocean.txt
lib/api/api_service_client.py
lib/auxiliary/data_ops.py
lib/clouds/do_cloud_ops.py
lib/clouds/shared_functions.py
scenarios/common.py
scripts/common/cb_common.py
scripts/common/cb_timebound_exec.py
util/openvpn/client.conf.template
util/openvpn/client_connected.sh
util/openvpn/server.conf.template

First, make the codebase use UTC timestamps instead of local timestamps.
There are other calls to time.time() which may still not be in UTC,
but this at least fixes all calls to datetime.now() to use datetime.utcnow()
instead.
There is one example in this patch showing how to repair calls to time.time()
if needed.
Second, Repair broken VPN_ONLY support ---- please see comments inline in the code.
VPN_ONLY is supposed to be checked for in the code and client_connected.sh
should be responsible for calling redis-cli *inside* the VM only after
then VPN connection is confirmed established and the only way to do that
is for the VPN client to execute the script.
Finally, add additional DigitalOcean defaults that were missing.

UTC timestamps, VPN problems, and DigitalOcean defaults.

---

scripts/common/cb_common.sh

Repair SYSLOG vpn support as well only when both VPN_ONLY and USE_VPN are used.

Repair SYSLOG vpn support only when both VPN_ONLY and USE_VPN are used

---

lib/api/api_service_client.py
lib/auxiliary/data_ops.py
lib/auxiliary/gui.py
lib/clouds/do_cloud_ops.py
scenarios/common.py

UTC support was still broken because we were still using datetime.fromtimestamp()
instead of datetime.utcfromtimestamp()

UTC Bugfix

---

configs/templates/_digitalocean.txt
lib/clouds/do_cloud_ops.py
lib/clouds/ec2_cloud_ops.py
lib/clouds/shared_functions.py

This commit unifies cloud-init based support for bootstrapping OpenVPN connections. It enhances EC2 to use the mechanism in exactly the same way that DigitalOcean does, sharing code to send the appropriate user-data without duplicated any code.
It has been tested with all of the SPEC Cloud 2016 applications on our own Amazon EC2 account and works well from a laptop outside of Amazon running CloudBench connected through an OpenVPN server running on Amazon which then deploys workloads also on Amazon.

VPN support for Amazon EC2

---

lib/operations/active_operations.py
util/openvpn/client.conf.template

We need to be able to set this to False in the configuration file.
If you need this as True, then please set it to true in your configuration file.

VPN: Do not auto-enable START_SERVER

---

scripts/common/cb_common.py

So, most of the UTC repairs we performed last year were correct, except for this one.
Unix "epochs" by themselves are timezone-less. It's when they are "interpreted" as human-readable
timestamps that they are parsed by python incorrectly.
When these epochs (from time()) are directly compared to each other, they are timezone-less,
and do not need to be offset.
But, when they are "fed" to python to be converted as human-readable, those rare cases are
when the timezones get lost.
We've already handled correctly in the past when human timestamps are compared to human
timestamps --- that all works fine --- no repair needed there.
However, the mongodb gmetad adapter also was doing this wrong --- see the PR associated with it.

One more UTC bugfix for the road

---

lib/operations/active_operations.py

Load Manager bug fix: Looping too fast on "stopped" AIs
One-line fix to make the load manager stop taking up 100% CPU
when SPEC sets the AI state to "stopped"

Load Manager bug fix: Looping too fast on "stopped" AIs

---

lib/operations/base_operations.py

The provisioning violation checks were happening long after the AI
had already been successfully provisioned within tolerance. This
fix ensures that checks do not happen during the "reset" phase
of the load manager.
Marcio, please double-check this PR. I did two tests:
1. Full spec run ----- normal run counts
2. Then, I artificially did `typealter hadoop hadoopmaster_sla_provisioning_target 10` and verified I got this error message: `Ran out of time to run generic post_boot scripts due to the established SLA provisioning target.`
Everything looks good on my end.

Runcount issue bugfix

---

lib/auxiliary/gui.py
lib/clouds/do_cloud_ops.py
scripts/common/cb_common.sh
scripts/ibm_daytrader_ppc64le/cb_setup_ramdisk.sh
scripts/mongo_ycsb/cb_restart_mongo.sh
scripts/mongo_ycsb/cb_restart_mongo_cfg.sh
scripts/open_daytrader/cb_setup_ramdisk.sh

1. We formally released block storage support *today* out of beta. NOTE: libcloud must be upgraded for it to work.
2. The 'mkfs` command used by all the CB scripts was not making use of the '-F' force flag. Without it, the flag cause mkfs to wait on standard input to type 'Y' in some cases.
3. The GUI was not handling some cases of 'last_known_state' and not showing filters correctly.

DigitalOcean block storage volume support

---

lib/clouds/do_cloud_ops.py
lib/operations/active_operations.py

The calculation in the submitter is always negative, and thus always causes the submitter to sleep for (5 / 10) = 0.5 seconds, which always appears to be spinning at 100%. Two submitters doing this thus takes up 2 whole cores. 
Using the absolute value instead fixes the problem ---- but I'm not entirely sure if that's what you were going for @maugustosilva.
The second commit is for DigitalOcean --- a printing error.

Fix for submitter always at 100% CPU

---

lib/auxiliary/gui.py
lib/clouds/do_cloud_ops.py

1. This is a driver-only fix which makes sure we do the proper libcloud-initializations during the aidefine() function.
2. We also have some minor GUI cleanup issue in here in the way numbers were detected and displayed that also relate to provisioning time in libcloud-based drivers.

SPECCloud: Fix wrong DigitalOcean provisioning time

---

lib/api/api_service_client.py

This parameter was missing too. To be totally honest, I'm not sure
why the harness was working in the first place without this parameter.
(I don't know how many months back the extra parameter appeared, but
this one was missing too).

SPEC v1.1: another missing API parameter

---

lib/clouds/libcloud_common.py

I tried my best to get the super-class perfect, but I just missed a single line of code. =) Silly me.
But this is a good example of fixing a bug that's common to all libcloud adapters without having to modify everybody's adapter at the same time.

one-line fix to restore libcloud multi-tenancy

---

clients/list_vms.go
lib/api/api_service_client.go
lib/operations/base_operations.py
scripts/common/cb_common.sh

1. Introduce golang bindings for CloudBench. (yay)
2. This commit also includes a slight modification to
the way logging works in "scalable" mode. Until now,
when using scalable mode, logs from the VMs were disabled.
But, Marcio recently introduced "~/cb_os_cache.txt" some
time ago (very nifty) which saves us the network latency and
no longer requires querying Redis on every log entry. This commit
uses that functionality and restores logging in scalable mode.

Gobindings and logging changes

---

scripts/btest/cb_run_btest.sh
scripts/common/cb_common.sh
scripts/common/cb_post_boot.sh

This enhancement installs a command into /etc/rc.local that allows
an application to restart itself after a hypervisor reboots.
It doesn't work very well with hadoop, but it works perfectly with
Cassandra.
Hadoop seems to be much more complex to automatically restart a VM
that has already joined the cluster. Requires more investigation.

Auto-restart load manager

---

lib/auxiliary/code_instrumentation.py
lib/operations/passive_operations.py

This commit significantly improves "monextract" performance
by reducing memory usage and adding more calls to the database
and by removing the sort when not necessary.
I also included a little utility function here which you can point at ANY python object
to determine the true, in-memory size of the object.
We can use this function for further trimming CloudBench memory usage in the future.

monextract performance

---

lib/operations/passive_operations.py

If you put a key that we don't use into the configuration file, like this:
`[FOO]`
That breaks the GUI and CLI support for the `cldshow` command.

unsupported config file keys

---

lib/clouds/libcloud_common.py
lib/clouds/shared_functions.py
lib/operations/active_operations.py
lib/operations/base_operations.py
lib/remote/process_management.py
util/openvpn/client_connected.sh

So, I'm not all that proud of this patch, but I had a hard time thinking of a better solution.
While floating IPs and private IPs stay the same, VPN addresses can (and do) change a lot.
On the orchestrator-side, we already have solutions for this in place that allow the orchestrator
to update it's IP address on-the-fly in case your laptop restarts or the connection resets.
But, on the VM-side, if a VPN connection resets, you're SOL without this patch.
The most important part of this patch is not just the VM-side that updates Redis with the
new IP, but really is the SSH-side of this which *dynamically* contacts Redis to get the
most recently-known IP address before each attempt to retry an SSH command.
Patching the retry support was not so straight forward: Now, instead of embedding the IP …

Support for VPN connection errors

---

kvm-qemu/base/centos_commands
kvm-qemu/base/extra_nic.cfg
kvm-qemu/base/fixdefaultgw.service
kvm-qemu/base/fixdefaultgw.sh
kvm-qemu/base/ubuntu_commands
kvm-qemu/build_common.sh
kvm-qemu/build_orchestrator.sh
kvm-qemu/build_workloads.sh

This commit brings the ability to automatically create kvm-qemu images
(both Orchestrator and Workloads). It relies heavily on a recent version
of the utility `virt-customize` (libguestfs 1.34).
A whole set of Workload and Orchestrator images were created and fully
tested through regression (real application) test. Will add
documentation on the wiki as soon as this commit is merged.

Ability to automatically build qcow2 (kvm/qemu) images

---

scripts/common/cb_common.sh

Prevent run_limit from going below 0 and stop executing loads when this
counter reaches 0 not -1.

Fix: prevent run_limit from getting negative and stop at 0

---

lib/clouds/osk_cloud_ops.py

Novaclient's add_floating_ip() API was removed in Queens release [1].
That causes cbtool fails to associate floating IP with VM when using
latest OpenStack release. The change replaces it with neutronclient's
update_floatingip().
[1] https://review.openstack.org/#/c/532999/

Replace outdated add_floating_ip() with update_floatingip()

---

configs/templates/_os.txt
lib/clouds/os_cloud_ops.py

Keeping up-to-date with changes in the myriad of OpenStack Clients
has been a problem for us for a long time. This update introduces
an alternative adapter for OpenStack clouds, leveraging the work
done on libcloud (OpenStack backend). For now, I propose we let the
two adapters to co-exist, and as we harden and mature this code, we
can obsolete the other adapter.

Libcloud-based adapter for OpenStack.

---

configs/templates/internal_options.txt
lib/operations/active_operations.py
lib/operations/base_operations.py

Workload Image building directly from CLI/API: initial support for
it was introduced a while back, but full use of this feature has
always been limited due to the fact that not all workloads map nicely
to a single image. An example: we us a single image - and thus a single
Dockerfile - for all YCSB workloads, be it MongoDB, Redis and Cassandra.
With the updates made here, CBTOOL now is able to properly map AI types
to Dockerfiles, automatically extracting the correct paramaters to call
the automated installer (just remember, the automated installer parses
the Dockerfiles to figure which commands to execute).
This means that a CLI/API call such as `vmattach check:<BLANKIMG>:
<DEFUSER>:nullworkload:build` will result in the execution of the
automated installer (i.e., `~/cbtool/install`) …

Improvements for workload image creation (dynamic configuration)

---

clients/async_attach_application.py
clients/list_vms.go
lib/api/api_service.py

1. Our old pub/sub based attach (appinit) doesn't work so well right now,
so here's a hacky way to perform an asynchronous attach without it.
It depends on another hack (in the API), which I'm not proud of,
but it doesn't stop parallelism. It just makes individual requests a little
slower, even though they still happen in parallel.
We add a delay in the API for "ailist" to look for pending objects, but
unfortunately, the API needs some cleanup. There's a period of time (Seconds)
where between API requests (Detected at scale) where the API can return
"no" objects at all.
The only way to fix this temporarily is to add a delay....
The permanent way to fix this would be to ensure that the appropriate amount
of locking is introduced between ailist calls in such a way that when a pending
object …

Bandaid for asynchronous attachment

---

lib/operations/active_operations.py

There was another regression. I previously committed support
to allow you to specific keys in the configuration file that
are not explicitly used or unsupported / ignored.
That change was lost somehow.

Unsupported Keys regression

---

cbact

We had two issues:
1. We enabled TCP support, but had an initialization bug.
2. We also had an issue where the syslog parameters were not
being pulled by the load manager from the same place,
but we came up with a workaround for that.

Better rsyslog protocol handling

---

configs/templates/internal_options.txt
lib/operations/active_operations.py

This feature allows you to make the load manager pause after each
load ID is complete.
It allows you to "step" through the execution of the load manager
via the API in such a way that the client explicitly controls when
the load manager moves to the next load iteration.
This has the effect of allowing you to re-use the same virtual machine
for more exploratory tests without making a new VM.
The way the feature works is that you have two options:
1. Pause after initial AI attachment.
2. AND/OR Pause after each load ID has completed.
In either case, by issuing polling for the state field via the API,
you will know when the load manager has paused.
Subsequently, a client then issues "statealter.... attached" to
instruct the load manager to unpause and perform another iteration.
Additionally, …

"Step"-through support for the load manager

---

lib/operations/active_operations.py
util/openvpn/client_connected.sh

Somehow there was a regression here. I introduce a change some time ago
that allows the post-boot process to "survive" live changes in a VM's
IP address.
This originally worked by having the SSH command timeout in combination
with having the VM itself update its record in redis.
But, the active_operations.py code that actually initiated the SSH
command (Based on UUID instead of IP address) seems to have been
accidentally reverted.

VPN Regression / fix

---

configs/cloud_definitions.txt
lib/clouds/do_cloud_ops.py
lib/clouds/libcloud_common.py
lib/clouds/os_cloud_ops.py
lib/clouds/vcd_cloud_ops.py

There were a number of errors that needed remedy:
1. Multi-tenancy's use of the comma ',' conflicted with keyword detection at the end of an 'aiattach' command.
One must now use a semicolon instead of a comma to separate tenant authentication in your config file.
2. The 'vmcreate_kwargs' dictionary must be reset on every invocation.
It holds values that are specific to each VM create, such as ssh keys and user data and cannot be
carried between invocations.
3. Vcloud was "probably" broken, although I have no real way to test it.
4. Use of private SSH keys was still broken, when one wants to use keys that are already pre-existing in one's account.
5. Libcloud-based adapters were still causing Redis tagging conflicts because public clouds have no "real" central API ip address.
6. …

Bugs in the libcloud adapter

---

lib/clouds/shared_functions.py

1. We attempt to inject a file in to /etc/apt for old VM images in such
a way that Ubuntu "unattended-upgrades" are prevented from happening.
This doesn't always work, but it helps. We recommend that the install
script be modified to get rid of unattended upgrades during install time.
2. A modification to `cloudinit_packages` was made incorrectly. This fixes that.

Cloud-init bugfixes

---

lib/clouds/shared_functions.py

This shouldn't be here. It breaks on RHEL.

Revert ubuntu-specific change

---

docker/orchprereqs/Dockerfile-centos_cb_orchprereqs
docker/orchprereqs/Dockerfile-ubuntu_cb_orchprereqs

The current installation script doesn't install bc and jq if these two packages are absent. With this change it installs them automatically.

Add installation commands for bc and jq packages.

---

scripts/fio/cb.fiojob.template

The fio profile is configured to be time based, but without the
time_based option in the profile, it can exit before the expected
runtime (when it has completely read/written the target file).

Fix: the FIO workload needs time_based

---

scripts/common/cb_common.sh

A recent commit added variables like HADOOPSLAVE_DATA_DIR and
HADOOPMASTER_DATA_DIR to virtual_application.txt of hadoop workload,
and they have the same value as DFS_DATA_DIR [1]. This breaks hadoop
workload because with that change the directory is created by
automount_data_dirs() and has root as its owner. Since hadoop datanode
service runs as cbuser, it can't write to that directory and fails to
start. The change fixes the issue.
[1] commit 3fa27ac53d5f0682e8d91c9f7e632996e1e29922

Fix ROLE_DATA_DIR permission when it's a plain old directory

---

lib/operations/active_operations.py
lib/remote/process_management.py

After enabling COLLECT_FROM_HOST, I observed the issue consistenly if I
exited cbtool without detaching VMC or cloud and restarted it with --soft_reset
option:
status: Host OS performance monitor daemon (gmetad.py) started successfully.
The process id is [] (using ports 8653 and 8653).
This occurs due to a few bugs with gmetad startup code:
- One is with ProcessManagement.start_daemon(). Note that get_pid_from_cmdline()
returns an empty list when it fails to find matching process. In that case,
start_daemon() returns a list containing one empty list. The value is not
considered empty in Python and makes cbtool mistakenly thinks the process
was started successfully although it wasn't.
- Another is with ProcessManagement.get_free_port(). It allocates the same
port when being called multiple …

Fix a few bugs with gmetad startup code

---

lib/operations/active_operations.py
lib/remote/process_management.py

Reverts ibmcb/cbtool#223
@rayx Greetings, my friend. This commit is causing an issue during initial startup of cbtool. What happens is something like this:
```
mariner@mariner-amazon-us-east-1:~/cbtool$ pkill -9 -f redis
mariner@mariner-amazon-us-east-1:~/cbtool$ ./cb -f 
Cbtool version is "8c5fe37"
Parsing "cloud definitions" file..... "/home/mariner/cbtool/lib/auxiliary//../..//configs/mariner_cloud_definitions.txt" opened and parsed successfully.
Checking "Object Store"..... Unable to detect a private Redis server daemon running. Please try to start one (e.g., redis-server /home/mariner/cbtool/lib/auxiliary//../../stores/mariner_redis.conf)
Parsing "cloud definitions" file.....
```
This is very reproducible. So, for the short term, I'm going to revert this. Can you take a look and see …

Revert "Fix a few bugs with gmetad startup code"

---

scripts/cassandra_ycsb/cb_restart_node.sh
scripts/cassandra_ycsb/cb_restart_seed.sh
scripts/cassandra_ycsb/cb_run_ycsb.sh
scripts/cassandra_ycsb/cqlsh_create_keyspace.cassandra
scripts/cassandra_ycsb/cqlsh_remove_keyspace.cassandra
scripts/cassandra_ycsb/virtual_application.txt
scripts/common/cb_ycsb_common.sh

After extensive testing with SPEC Cloud baseline, where numerous and
painfully complicated new modes of failure for Cassandra were uncovered
significant changes were introduced to make the workload more robust.
In addition to it, significant bugs were fixed (such as removing
the incorrect YCSB backend profile detection, which is now explicitly
specified). This code was well tested on both Docker and Libvirt clouds.

Cassandra YCSB bugfixes and improvements.

---

lib/clouds/gce_cloud_ops.py

I'm working on another PR to actually handle
VM deletes the way we discussed, but this at least
allows GCE to return a clear message.

GCE: return a clear error message on deletes

---

lib/clouds/libcloud_common.py

Sometimes, if a region is unavailable in libcloud we want
to indicate clearly that it has become unavailable without
a stack trace that hides the issue.

libcloud: Also return better error

---

cbact
lib/auxiliary/cli.py

At scale, TCP logging at scale performs much better than UDP when sending
logs over the internet.
TCP logs from any `cbact` processes were getting lost due to line
breaks because of this bug: https://bugs.python.org/issue12168
With this change, if the TCP protocol is chosen, we override
the syslog handler class to fix the line break to use a newline
so that logs are received properly.

rsyslog: Unbreak TCP linebreaks

---

lib/operations/passive_operations.py

We use the string "C+<NUMBER>" or "C-<NUMBER>" to identify the need
to increase or descrease an atomic counter. This patch ensures that
we don't accidentaly trigger this behavior with UUID (where the string
"C-" might occur.

Counter increment/decrement fix.

---

lib/operations/active_operations.py

Use the value of the VM attribute "generic_post_boot_command", instead
of the prefixed "./scripts/common/cb_post_boot.sh". Required for the
"building workloads on the fly while deploying against unconfigured
images" functionality.

Fix for the ability of deploying workloads using unconfigured images.

---

lib/clouds/osk_cloud_ops.py
lib/clouds/shared_functions.py

Fix the wrong message in OpenStack by properly differentiating between data volumes and boot volumes from base images.

Fix for wrong message in OpenStack clouds

---

configs/templates/PUBLIC_dependencies.txt

Changed the dependencies for the newly contributed `rrdtool graphing`
tool, to ensure that it gets installed only on the Orchestrator image
(as it is now, the automated image building is broken for workload
images).

Dependecy fixes

---

lib/clouds/os_cloud_ops.py

Simple update to fix instance deployment in OpenStack clouds where the RegionName is empty (affects only the libcloud-based, OpenStack cloudbench adapter).

OpenStack libcloud fix

---

docker/build_common.sh
docker/workload/Dockerfile-centos_cb_netperf
scripts/common/cb_common.sh

This bugfix ensures functionality in a scenarios where Docker instances 
are used without "Docker volumes".
Bugfix for automated building of netperf centos images.

Bugfix for SPECCloud (Hadoop/KMeans) on Docker

---

scripts/sysbench/cb_restart_mysql.sh
scripts/sysbench/virtual_application.txt

1. Change the amount of RAM used by mysql on the fly
2. Make the location of the mysql cnf file configurable.

sysbench: add more tunables

---

configs/templates/internal_options.txt
lib/auxiliary/gui.py

1. Set the default unchanged string to None
2. Modify the GUI so that file listings (e.g. SPEC FDR reports) are available
in the UI directly in both ~/cbtool as well as ~/osgcloud/cbtool

Minor updates

---

lib/clouds/shared_functions.py

This is a critical fix for public clouds: Infinite destroy was not
working properly because the common logging code was throwing an
exception on failure that we were not prepared to handle. Now we
handle those and actually attempt to do the retry delete and it
appears to be working now (primarily for GCE which throws a lot of
timeout errors.)

fix broken infinite retry

---

lib/clouds/kub_cloud_ops.py
scripts/common/cb_common.sh
scripts/common/cb_hadoop_common.sh

k8s presents two additional problems:
1. Because of the way k8s does networking (flannel), applications
that identify themselves by IP address don't work anymore, due
to the way NAT-ing is done in the Kubernetes overlay network.
As a result, applications can only use the names that CB
provides in /etc/hosts
2. Also, for the same reasons, k8s tends to recycle IP addresses a lot,
after applications are destroyed and re-created. As a result, this causes
redis tagging conflicts. This means the `cloud_ip` variable has to be
absolutely unique in Redis.
This commit does the following:
1. Set the required Hadoop XML properties to use names instead of IP addresses.
2. Make sure that the shell scripts use `run_cloud_ip` instead of `cloud_ip`
to discover each other.
3. Make cloud_ip 100% unique so …

k8s: additional compatibility

---

lib/operations/passive_operations.py

This allows the `applist` command to return the state value as a key/value in the returned dictionary output. Currently, it's not there.

API: add state to 'list_objects' command

---

lib/clouds/libcloud_common.py
lib/clouds/shared_functions.py

We need the ability to log HTTP headers to debug what happens
with libcloud, but libcloud doesn't make that easy, so we have to
bypass it.
What we're trying to do here is solve a conundrum. Under the covers,
libcloud uses /usr/lib/python2.7/httplib.py as it's primary HTTP
transport library.
httplib, has the ability to debug itself, but instead of using the logging
library like a "good" python library should, it just prints to stdout.
In a separate patch (via Dockerfile) we fix httplib to work correctly
and use a logger.
That being said, after it uses the logging library correctly, we still
have to capture the log output the headers ONLY when something bad happens.
We don't want to spew a bunch of header logs to the logging system
for the 99% of the time when things are working fine.
To …

libcloud: ability to log http headers

---

docker/workload/Dockerfile-ubuntu_cb_kernbench
scripts/kernbench/cb_run_kernbench.sh
scripts/kernbench/cb_start_kernbench.sh
scripts/kernbench/dependencies.txt
scripts/kernbench/kernbenchloadgen.sh
scripts/kernbench/virtual_application.txt

Add the kernbench workload, each run cleans up the tree, make a
defconfig and then compile the kernel with the specified amount of
compiler threads (default is 4 * cpus).

kernbench workload

---

lib/clouds/libcloud_common.py

For whatever reason, there were one to may destroy() operations being submitted. Let's fix that.

libcloud: Don't delete too many times

---

configs/templates/internal_options.txt
lib/clouds/shared_functions.py

After a snapshot is created, often we still need to attach to a VM's serial console, but sometimes we want a username to be installed with sudo access in the VM without requiring network access to create that user.
As long as we have cloud-init, we can do that on the fly, regardless how old the snapshot is.
Example:
> CLOUDINIT_SUDO_USER = cbtool
> +# Use the 'openssl' command to choose a password to enable this feature. 
> +# Requires cloud-init support.
> +CLOUDINIT_SUDO_PASSWD = $False # Disabled by default
Instead of `False`, you just input a salted password (example using the openssl command) just like you would in the shadow file.
This allows the user to choose (at boot time) whatever service account for debugging purposes that they want without having to ask for the snapshot to be …

Support for service accounts

---

scripts/kernbench/cb_run_kernbench.sh
scripts/kernbench/cb_start_kernbench.sh
scripts/kernbench/virtual_application.txt

Fixes for Kernbench

---

scripts/cassandra_ycsb/virtual_application.txt
scripts/common/cb_common.sh
scripts/common/cb_hadoop_common.sh
scripts/giraph/virtual_application.txt
scripts/hadoop/virtual_application.txt
scripts/mongo_acmeair/virtual_application.txt
scripts/mongo_ycsb/virtual_application.txt
scripts/open_daytrader/virtual_application.txt
scripts/redis_ycsb/virtual_application.txt
scripts/scimark/virtual_application.txt
scripts/specjbb/virtual_application.txt

Improvements for JAVA-based workloads

---

scripts/bonnie/cb_run_bonnie.sh

Fix for bonnie

---

scripts/cassandra_ycsb/cb_restart_seed.sh
scripts/cassandra_ycsb/virtual_application.txt

Fixes for Cassandra/YCSB

---

scripts/filebench/cb_run_filebench.sh

Fixes for Filebench

---

scripts/common/cb_common.sh
scripts/common/cb_post_boot.sh

1) Given that some workloads (e.g., Hadoop) make use of bashrc,
cb_post_boot now ensures that ~/.bashrc always exists during
initial execution.
2) Make sure that function `check_container` always returns the
correct number of cpus and and amount of memory
3) Make sure that function `mount_filesystem_on_volume` will not
accidentally "double mount" filesystem, whether executed on containers
or on VMs/Bare-Metal.
4) Add a new function, `fix_ulimit` which prevents application-level
errors due to open file description exhaustion (among others)
5) Make sure that directories are automounted as early as possible
(the function `automount_data_dirs` and associated functions are
idempotent, so it shouldn't be a problem calling it during the
generic startup, and let developers to call it again during …

Improvements and bugfixes for instance configuration auxiliary functions

---

configs/templates/_kub.txt
lib/clouds/kub_cloud_ops.py

Add support for "image pull policy" and the use of "secrets" on
Kubernetes adapter. The secret has to be created on the K8S cluster
prior to CB use.

K8s adapter enhancement.

---

lib/clouds/libcloud_common.py

We need the ability to log HTTP headers to debug what happens
with libcloud.
For the response HTTP headers, that's not problem => We get that
from the libcloud library itself.
For the request headers, libcloud doesn't make that easy, so we have to
bypass it.
What we're trying to do here is solve a conundrum. Under the covers,
libcloud uses /usr/lib/python2.7/httplib.py as it's primary HTTP
transport library.
httplib, has the ability to debug itself, but instead of using the logging
library like a "good" python library should, it just prints to stdout.
In a separate patch (via Dockerfile) we fix httplib to work correctly
and use a logger. We can't really monkey patch this, and sending a python
patch upstream would take too long
That being said, after it uses the logging library correctly, …

libcloud header logging

---

cbact
lib/auxiliary/code_instrumentation.py

We have two problems with logging over TCP. While TCP
is much more performant than UDP, it has a really crappy
implementation.
This fixes those issues.

rsyslogd: Make python survive TCP connection failures

---

lib/auxiliary/data_ops.py
lib/operations/active_operations.py
lib/operations/base_operations.py

We've had round-robin provisionig for a while, but it was not deterministic,
meaning that if you reset CB, the next time you create a batch of VMs,
there was no gaurantee the same VMs would go to the same places.
The commit makes it so that VMCs are sorted and then assigned VMs to them
in such a way that the head-VM of the the AI always goes first followed by
the remaining VMs in the AI in the same order in which they were assigned.
This is really important when you have a cluster of heterogeneous hypervisors
that have different sizes or different performance characteristics and
you want things to perform in the same way each time.

Fully deterministic round-robin scheduling

---

lib/clouds/do_cloud_ops.py
lib/clouds/libcloud_common.py

DigitalOcean in particular supports both names and IDs as image identifiers.
Additionally, if we issue a `cldalter` to change the image ID on the fly,
we need to be able to lookup that modified image ID without having to
reset CloudBench to be able to use it.

Cleanup libcloud image identification

---

scripts/cassandra_ycsb/cb_restart_seed.sh
scripts/cassandra_ycsb/virtual_application.txt
scripts/common/cb_common.sh
scripts/common/cb_post_boot.sh

1. Sometimes pulling large container images take a long time. Wait a bit longer.
2. Cassandra now has a configurable memory limit, which defaults to 50%.

workload changes: cassandra and containers

---

docker/workload/Dockerfile-ubuntu_cb_hadoop
docker/workload/Dockerfile-ubuntu_cb_ycsb
scripts/cassandra_ycsb/virtual_application.txt
scripts/hadoop/virtual_application.txt

docker: cassandra => 2.1.20, hadoop => 2.7.5, openjdk => 8
The docker container software didn't match what's currently
in the latest SPEC Cloud documention.

Update spec workload containers

---

scripts/stress/cb_check_stress.sh
scripts/stress/cb_run_stress.sh
scripts/stress/dependencies.txt
scripts/stress/virtual_application.txt

- The only other CPU-intensive sythetic workload in CB - coremark -
requires a manual download from an EEBMC url. The package `stress-ng` is
available in Ubuntu/RHEL repos readily.

New Application Instance type, based on the stress-ng workload

---

scripts/slurm/cb_config_slurm_cluster.sh
scripts/slurm/cb_run_slurm_cluster.sh
scripts/slurm/cb_start_slurm_cluster.sh
scripts/slurm/dependencies.txt
scripts/slurm/mariadb_create_database.sql
scripts/slurm/mariadb_list_database.sql
scripts/slurm/virtual_application.txt

- SLURM is a free and open-source job scheduler for Linux and Unix-like
kernels, used mostly in HPC environments.
- This initial implementation in CB takes care of creating the Slurm
cluster and making sure all the nodes join properly. In a future
expansion, will add support for running multiple applicatons (load
generating processes) via Slurm.

New Application Instance type: SLURM

---

scripts/common/cb_common.py
scripts/common/cb_common.sh
scripts/common/cb_post_boot.sh
scripts/common/cb_report_app_metrics.py

- When an user specifies, in the AI-specific <ROLE>_DATA_DIR attribute
the value "none" (indicating that a given application will use the volume without a filesystem on it), the function mount_filesystem_on_volume can now be called without resulting in error
- The function check_container now correctly detects the number of CPUs and amount of memory available, in KB.
- Make sure every other function (e.g., haproxy_setup) uses the function check_container

Improvements and bugfixes in common bash functions

---

lib/clouds/shared_functions.py

Somehow, recent versions of Ubuntu changed behavior in such a way
that openvpn is getting started twice. At some point in the past,
I began starting openvpn via cloud-init manually because Ubuntu
wasn't doing the right thing, but it appears to have been fixed
so let's stop doing that.

stop the VPN from starting twice

---

cb

In newer versions of python 2.7 (presumably v3 as well) when
combined with Ubuntu 18.04, the `readline.write_history_file` function
has changed to actually use the `rename` system call instead of
updating the history in place.
This causes problems in Docker-based environments, because we attempt
to preserve the CB history file by including it via `docker -v` as
a bind mount. Since python is unable to replace the file (Because
the container doesn't own it), this fails.
The solution is to use a temporary file and move the contents of the
temporary file to the bind-mounted file.
This solution should work with and without docker as well and be transparent.

broken readline history file function

---

scripts/common/cb_common.sh

If connectivity is lost in the middle of the boostrapping the container,
we can sometimes get into a state were the container actually did startup
but we didn't realize it. So we need to doubly-check whether or not
we're actually running inside a container.

fix for when nested container SSH loses connectivity

---

configs/templates/internal_options.txt
lib/clouds/ec2_cloud_ops.py
lib/clouds/gce_cloud_ops.py
lib/clouds/kub_cloud_ops.py
lib/clouds/libcloud_common.py
lib/clouds/slr_cloud_ops.py
lib/operations/base_operations.py

In public clouds, it's quite common for the load balancer to receive
traffic from the internet but actually load balance to the private network,
causing both virtual interfaces to experience load.
Let's support that.

Public-network haproxy

---

lib/clouds/libcloud_common.py
scripts/common/cb_common.sh

From time to time (for whatever reason) VMs can go offline during a benchmark.
In public clouds, this should be transparent by design. The user is not supposed
to "care" that VMs experienced transient issues like that from the perspective
of the API of the respective cloud provider.
If a hypervisor dies and causes a VM to go offline, while this obviously sucks,
CB should not simply "trust" that the cloud is going to bring the VM back online,
because this can cause our interpretation of benchmarks to be wrong.
Our policy (from the libcloud perspective) for public clouds during these error
condtions is zero tolerance: If at ANY time something bad happens during the process
of running a benchmark, we simply don't allow it.
Thus, during a reset of the benchmark, if a VM suddenly went offline, …

Pause on offline droplets

---

lib/clouds/kub_cloud_ops.py
lib/stores/stores_initial_setup.py
scripts/common/cb_common.sh

1. Don't kill rsyslogd if the mode is 'shared'
2. Handle Redis hostnames if the hostname has a `-` character in the hostname

Minor bugs

---

lib/operations/base_operations.py
scripts/common/cb_common.sh

From now on, when `appnoload`/`dont_start_load_manager` is set, we
actually execute the load manager, but in "debug" mode. This means that
all load manager startup scripts are created on the correct instance(s),
but they are not actually executed. This change makes the current code
compatible with the updated documentation in
https://github.com/ibmcb/cbtool/wiki/HOWTO:-Debug-initial-setup, and
especially https://github.com/ibmcb/cbtool/wiki/FAQ-U#uq19.

This commit greatly improves the debugging of the Load Manager.

---

configs/templates/_do.txt
configs/templates/_dok8s.txt
configs/templates/internal_options.txt
docker/workload/Dockerfile-centos_cb_nullworkload
docker/workload/Dockerfile-ubuntu_cb_tpcc
scripts/hpcc/cb_run_hpcc.sh
scripts/scimark/cb_run_scimark.sh
scripts/tpcc/cb_reset_mysql.sh
scripts/tpcc/cb_restart_mysql.sh
scripts/tpcc/cb_run_sysbench.sh
scripts/tpcc/dependencies.txt
scripts/tpcc/virtual_application.txt

This is the TPC-C workload from Percona for MySQL in sysbench.
As expected, this is a pretty noisy benchmark, so it is advised to have runs of at least 5 minutes and experiment with the MySQL tunables exposed.
This PR also includes a couple of small fixes we noticed while building the workload.

Add the TPC-C workload

---

configs/templates/internal_options.txt
lib/operations/base_operations.py
scripts/common/cb_common.sh
scripts/common/cb_post_boot.sh

By setting the attribute CONFIGURE_FIREWALL to $True (default), a new
configure_firewall function will be run during the "post-boot" phase,
making sure that instances can be accessed only by the Orchestrator
node and instances that are part of the same AI. The main use case for
it is public clouds where instances get a directly accessible public IP.
While an experimenter can (and should) configure the cloud-specific
controls for "virtual networking security groups", at a small cost in
terms of code, we can provide a cloud-agnostic solution that should
protect everything out of the box.

Add ability to automatically configure firewall on instances

---

scripts/common/cb_common.sh
scripts/common/cb_post_boot.sh

A large portion of CloudBench-supported cloud providers allow for multiple
vnics in a single instance. With this commit, CB can deal with it, not
only by automatically detecting and runnning dhclient on multiple
additional vNICs, but by also collecting all the IP addresses and
storing those on the VM-specific variable "extra_cloud_ips".

Add ability to deal with multi-vnic instances

---

scripts/common/cb_common.sh
scripts/common/cb_post_boot.sh
scripts/iperf/cb_check_iperf_server.sh
scripts/iperf/cb_run_iperf.sh
scripts/netperf/cb_run_netperf.sh
scripts/nuttcp/cb_run_nuttcp.sh
scripts/xping/cb_run_xping.sh

In addition to a new function (set_mtu) which is common to all
workloads (and will fail in case it does not succeed in setting the
specified mtu), this commit also makes sure that all network-centric
workloads properly uses this function (this is done mostly by removing
old duplicated code)

A more robust and standardized function to set mtu for vnics

---

configs/cloud_definitions.txt
configs/templates/_kub.txt
lib/clouds/kub_cloud_ops.py

K8S has a lot of scheduling options. This commit further extends use of those
choices to use "nodeSelectors" so that CB can issue new pods without having
to actually choose a host while the hosts that we care about are grouped together
on the k8s-side of the house instead of specifying them explicitly in our configuration.

node selector support

---

configs/templates/internal_options.txt
lib/clouds/libcloud_common.py
lib/clouds/shared_functions.py

A common error-handling issue with public clouds is detaching VMs.
Currently, we have a mechanism already (that we depend on a lot, actually)
that will attempt to repetively detach resources forever until it succeeds.
This is really important when we are spending money on a public cloud
running a benchmark.
This commit allows this mechanism to backoff during this waiting period.
Rather than re-submit the same detach request every 5 seconds, it provides
a very simple backoff mechanism that you can configure a maximum for,
so that we don't inundate the cloud with too many operations to perform,
particularly if the cloud is transiently unavailable.

Incorporate a basic destroy-time backoff mechanism

---

lib/clouds/shared_functions.py
lib/operations/base_operations.py
scripts/common/cb_common.sh

Previously (for the wrk2 workload), we introduced a change that
allowed ingress haproxy traffic to come in over the public network, while
allowing egress haproxy traffic to exit over the private network to
mimic our customers.
Don't do this if there is no haproxy in the picture. =)
The problem with doing this is that the firewall will block this traffic
if we really wanted.
As a result, I have also included a patch that allows access on the public
network for the firewall only from other dropls (just like the private network).

Don't use the public network if a load balancer is not enabled

---

lib/clouds/kub_cloud_ops.py

k8s versions 1.16 and higher no longer accept the string "extensions/v1beta1"
in the version field. (I'm not exactly sure what it's used for).
But, by switching this field (And monkey patching the pykube library) to
"apps/v1" => things start magically working again. =)

k8s bug in newer versions

---

lib/operations/base_operations.py

Don't delete the logs from /var/log/cloudbench if the logstore is in shared mode.

Don't flush shared logs

---

configs/templates/internal_options.txt
lib/clouds/gce_cloud_ops.py
lib/clouds/shared_functions.py

"extended" means that we will append the AI name and VM roles
to the end of the VM's name for rsyslog purposes. This is rather
convenient because it translates to the VM's hostname which makes
log messages easier to lookup when you know the AI and role information.
Also "sneak" in a GCE threadsafe bugfix, while we're at it. =)

Optional Extended instance names

---

configs/templates/internal_options.txt

Kernbench was only added to container templates so far.
Add a kernbench entry to vm_templates to make it runnable
inside a VM.
Signed-off-by: Jan Glauber <jglauber@digitalocean.com>

Add missing kernbench config entry

---

lib/stores/mongodb_datastore_adapter.py

In an environment like hours were a few people were using the same
database over a long period of time, the list of experiment IDs
was getting too long.
This is a temporary workaround, but we'll need a more permanent solution.

Bug enumerating experiment IDs

---

scripts/common/cb_common.sh

We introduced a bug when attempting to update the redis cache
inside of a VM. Fix it.

Fix redis cache bug

---

lib/operations/passive_operations.py

This code is a relic from another era. We used to run multiple cloud
attachments in the same CB instance, which is still supported, but
not while the VPN is running. Just don't do that anymore.

Remove dynamic API binding logic

---

docker/orchestrator/Dockerfile-centos_cb_orchestrator
kvm-qemu/base/ubuntu_commands
lib/auxiliary/data_ops.py
lib/clouds/pdm_cloud_ops.py
lib/clouds/shared_functions.py
lib/operations/active_operations.py
scripts/tpcc/cb_restart_mysql.sh
setup.py

We've fixed a number of issues to stabilize the adapter.
1. Move to more updated/maintained version of the python docker bindings.
2. Use the object-oriented version of the bindings.
3. Stop pre-caching images on startup. Only pull the image when the corresponding benchmark is requested.
4. Remove thread safety conflicts.
5. Support private and remote repositories.
6. Provide an example of a benchmark (like mysql) using a *different* memory allocation
in this kind of environment than when it runs in VMs.
7. Other things I cannot remember...

Harden the bare metal Docker adapter

---

lib/clouds/libcloud_common.py

We were previously (greedily) using count() instead of matching exactly.

libcloud: Match cloud names correctly upon deletion.

---

lib/stores/redis_datastore_adapter.py

When clouds share substrings in common, the wrong keys end up getting deleted.

Redis: flush only exactly the cloud that was requested.

---

scripts/fio/cb.fiojob.template
scripts/fio/cb_run_fio.sh
scripts/fio/virtual_application.txt

This adds support for some further FIO config options
within cbtool. Following FIO config params were added:
- thinktime
- thinktime_blocks
- rate_process
- bssplit
The default behavior is to not use them unless someone enable
them in the FIO based AI config.

Support additional FIO config options within cbtool

---

docker/workload/Dockerfile-ubuntu_cb_wrk2

It looks like commit 2a67bd1e0f291bd9afc872df2ca23b70df599dcf overwrote
the content of the wrk2 workload with the one from wrk. Fixing that
here.

Fix wrk2 docker file

---

lib/operations/base_operations.py
lib/stores/mysql_datastore_adapter.py

We faced an issue within cb in which when the code path
was touching this user-defined exception "MetricStoreMgdConnException"
python3 complained with following msg:
"TypeError: catching classes that do not inherit from BaseException
is not allowed."
Due to this, the client API object was getting hung and the client API kept
waiting to receive something from the socket. This fixes the issue
by using local version of MetricStoreMgdConnException class and
because of that we no longer see that TypeError msg.

fix MetricStoreMgdConnException issue

---

docker/workload/Dockerfile-ubuntu_cb_linpack
scripts/linpack/cb_run_linpack.sh
scripts/linpack/virtual_application.txt

Cb currently uses an Intel optimized linpack version which runs only
on Intel based systems. This updates Linpack workload to version 2.3
and it also adds support for running Linpack workload on AMD based
systems along with Intel based systems.  A new config option:
"linpack_version" is added which by default will just run the current
linpack version. However, if the user sets it to 2.3 then the updated
linpack version will run.

update Linpack workload to support AMD systems

---

scripts/common/cb_common.sh
scripts/common/cb_post_boot_container.sh
scripts/tpcc/cb_restart_mysql.sh

1. This PR speeds up container startup a little bit in the VM by using
better rsync options when the container is deployed.
2. We also provide initial support for hugepages
We spent some time testing hugepages in CloudBench.
Here are a handful of changes that help prepare to enable it in a nested
environment (particularly with the PLM adapter).
NOTE: We don't actually configure the guest kernel here yet in
CloudBench to choose the number of hugepages as that is HIGHLY dependent
on the application, but we do put the limits in place (and an example
option in MySQL).
For it to actually take effect, one would either need to reserve the
pages or turn on THP at the guest level via CloudBench in a followup PR.

Nested improvements

---

configs/templates/stores.txt
exclude_list.txt
lib/auxiliary/gui.py
lib/stores/mysql_datastore_adapter.py

1. MySQL supports regex, but we were not passing through those kinds of
queries correctly. Fix that. (This makes HOST-level ganglia metrics
work, particularly for the PLM adapter).
2. MySQL's data directory was being placed in the wrong place, the same
location as where the rsync operations occur, which was inadvertently
sending the entire local contents of the database to the VMs for no
reason. (This should have no effect when using a remote database, of
course.)

MySQL improvements

---

scripts/linpack/cb_run_linpack.sh

We missed adding load_level variable support in the newer linpack
version which we added recently. This addresses it.

Incorporate load_level support within new linpack_2.3

---

configs/templates/internal_options.txt
scripts/stress/cb_run_stress.sh
scripts/stress/virtual_application.txt

Occasionally, we want to just "fill up" all the memory of a guest VM.
This patch adds the ability to do that using a percentage.

allow memory stress flexibility

---

lib/auxiliary/dependencies.py
setup.py

Hello @mraygalaxy! I work with @jdesfossez at DigitalOcean. During some testing of `cbtool` on Python3.8, ran into an issue with the dependencies checker. As it turns out the `linux_distribution()` method was removed from the `platform` module in the standard lib in Python3.7.
Related Python Bugs (discussion about removing the method):
* https://bugs.python.org/issue1322
* https://bugs.python.org/issue28167
* Try to import `distro`. If version below 3.7, pass, else, raise
exception. `distro` is a requirement for Python >= 3.7
* Try to use `platform.linux_distribution()`. If an `AttributeError` is
raised (indicating the `linux_distribution` method is no longer
available), use `distro.name()`, `distro.version()`, `distro.id()` to
obtain the same information from the `distro` package.
* …

Fix dependencies Checker

---

configs/templates/internal_options.txt
scripts/coremark/cb_run_coremark.sh
scripts/coremark/cb_setup_cmk.sh
scripts/coremark/virtual_application.txt

A couple of changes needed to make coremark usable on a recent Ubuntu and have the input buffer configurable.

Fix coremark

---

lib/operations/active_operations.py
lib/operations/passive_operations.py
lib/remote/process_management.py
lib/remote/ssh_ops.py
scripts/common/cb_benchmarkstart.sh
util/cbssh.sh

When using CloudBench in a local environment where the SSH agent is in
use, we end up using the wrong identities. Make SSH use *only* the
identities specified by CloudBench when attempting to login to
CB-managed virtual machines.

Disable CloudBench use of ssh-agent

---

lib/clouds/libcloud_common.py
lib/operations/active_operations.py

1. Linode doesn't have the same power-on command as other clouds, so handle that better. We have a policy in cloudbench that we do not destroy offline instances (for evidence purposes, in case a VM or host was broken and needs to be investigated), so this is an important command.
2. I want to revert this commit from 2018:
commit 751de25fba78c99ed4db0b24d146a48fc9371a98
Date:   Fri Mar 2 10:12:37 2018 -0500
If we keep this commit, it causes our files to be owned by root inside the running containers instead of being owned by 'cbuser' and we're not able to startup successfully.

Linode followup bugfixes

---

docker/build_common.sh
docker/workload/Dockerfile-ubuntu-cb_stress
docker/workload/Dockerfile-ubuntu_cb_linpack
docker/workload/Dockerfile-ubuntu_cb_nullworkload
docker/workload/Dockerfile-ubuntu_cb_open_daytrader
docker/workload/Dockerfile-ubuntu_cb_tpcc
docker/workload/Dockerfile-ubuntu_cb_ycsb
scripts/linpack/cb_run_linpack.sh

Not all workloads are 22.04 (Jammy) compatible:
1. sysbench-tpcc support stopped at 20.04.
2. mongodb was removed as a native Ubuntu package and requires using the company's PPA
3. We are still pinning cassandra for SPEC Cloud purposes. Is that still necessary given the current state of SPEC Cloud development?
4. The linpack URL changed yet again.
5. python2.7 was still being used in some places. We need to finish deprecating that.
6. Add a workload dockerfile for stress-ng. (I thought I did that already, but I guess not)

Update workloads to 22.04

---

README.md
lib/clouds/lin_cloud_ops.py

1. Merged: https://github.com/apache/libcloud/pull/1946 (This will likely go into version 3.9.0, based on their current release schedule)
2. The use of metadata changed, so make cloudbench change accordingly.

Libcloud support for Linode merged

---

lib/stores/mysql_datastore_adapter.py

In recent tests we noticed that the tables names are being returned as byte arrays in python3 while `_latest_tables` and `_indexed_tables` contains regular strings, which leads to the failure of finding table correctly. 
For instance, `latest_management_VM_username` is shown as `bytearray(b'latest_management_VM_username')` in `_tables_found`. 
Convert the byte arrays to regular strings using UTF-8.

convert the byte arrays to strings using UTF-8 encoding

---

lib/stores/mysql_datastore_adapter.py

@mraygalaxy @mraygalaxy2  
A follow up PR for https://github.com/ibmcb/cbtool/pull/434
We also noticed in some other cases, the table names returned during cloudbench initialization were still regular strings. So use `try/except` to attempt to decode the table name `x[0]`. If it hits an `AttributeError`, then use the original `x[0]` instead.

Add try/except for using .decode attribute
